### ISSUE TITLE
General documentation (readme.md)

### ISSUE THREAD

**Issue by AJ311021** [DSE511-Team-Avatar/Team-Avatar#13]
Update a readme.md file and include a description of the structure of the repository and the problem that we are working on.

**Comment by AJ311021** [comment]
The file was updated with the most recent details and if further changes are required for the repository, this issue will be reponed.

**Comment by AJ311021** [comment]
At the end of the project, this document should be updated with information on what's in the repo and how to generate the results in the write up (main.py)

**Comment by AJ311021** [comment]
Need to update this with the information on code and how to run main.py

**Comment by AJ311021** [comment]
The text and general instructions are updated, only the repository structure scheme needs to be finalized.

**Comment by AEghasemi** [comment]
Done.
