### ISSUE TITLE
General documentation (requirements.txt)

### ISSUE THREAD

**Issue by AJ311021** [DSE511-Team-Avatar/Team-Avatar#14]
Add a requirements.txt file (or similar file) that starts tracking which libraries are being used in the project.

**Comment by AEghasemi** [comment]
The (requirements.txt) file is added. The required libraries will be updated soon.

**Comment by AJ311021** [comment]
Let's add the preliminary libraries and then close it.

**Comment by AJ311021** [comment]
This file was updated for Part1.EDA libraries, if more libraries are added in further parts, the document will be updated.

**Comment by AEghasemi** [comment]
Ok

**Comment by isifletcher** [comment]
I didn't need any extra libraries, so I didn't update this file.

**Comment by isifletcher** [comment]
@AJ311021, Can we close this issue or do you want to keep it open?

**Comment by AJ311021** [comment]
Let's keep it open, and at the end, check again all the libraries we have used, update this file if needed and then close.

**Comment by AJ311021** [comment]
I checked the requirements, no changes from my side after doing the modeling part

**Comment by AEghasemi** [comment]
The task is complete.
