### ISSUE TITLE
Add back the ocean proximity column

### ISSUE THREAD

**Issue by isifletcher** [DSE511-Team-Avatar/Team-Avatar#23]
Ehsan's code deletes the ocean proximity column when the preprocessing codes are combined. We need to figure out how to add it back. I created a Jupyter notebook with the combined codes. We can refer back to that one.

**Comment by AEghasemi** [comment]
We have to create several functions. Then we can use them in the main file. The code for cleaning just cleans the NA's. We can use it to take care of the Na's.

**Comment by isifletcher** [comment]
@AEghasemi :
Please don't close issues before they are solved. I added the code that includes that column now, but the issues help keep track of what is left, so if it is not done, please keep it open.
