### ISSUE TITLE
Final report

### ISSUE THREAD

**Issue by AJ311021** [DSE511-Team-Avatar/Team-Avatar#25]
We will need to write a final report based on our results.
4-6 page report in pdf format, using the IEEE template; at a minimum, the report should include the following sections: (see slides from the "how to write a research paper" lecture for tips on what should go into each section)

- Introduction/Problem
- Related Work (can be the second section or second to the last section)
- Data/Methods
- Results
- Discussion/Conclusion

Each member to update their respective parts in the report (considering each code's contribution):

- [x] Albina
- [x] Pragya
- [ ] Ehsan
- [x] Isi

**Comment by AJ311021** [comment]
Update your parts and important findings in the common google drive doc file: "Final report draft"

**Comment by isifletcher** [comment]
Link for the overleaf: https://www.overleaf.com/5162129199mwcgyxgqzsyq
