### ISSUE TITLE
Project parts division. Part 3. Modelling (b)

### ISSUE THREAD

**Issue by AJ311021** [DSE511-Team-Avatar/Team-Avatar#7]
- [x]  Random Forest [Isi]
- [x]  Model optimization (hyperparameters tuning)
- [x]  Basic error analysis using cross validation (mean squared error)
- [x]  Feature extraction/importance (Can experiment with different categories (features, columns) combinations for the models)

**Comment by AJ311021** [comment]
RandomForestRegressor has the relative importance of each attribute/feature for making accurate predictions: feature_importances_
Can use GridSearchCV().best_estimator_.feature_importances_
Link: https://scikit-learn.org/stable/auto_examples/ensemble/plot_forest_importances.html
We can discuss it later.

**Comment by isifletcher** [comment]
This link contains some explanations about GridSearchCV and the parameters: https://towardsdatascience.com/hyperparameter-tuning-the-random-forest-in-python-using-scikit-learn-28d2aa77dd74
