### ISSUE TITLE
Project parts division. Part 3. Modelling (c)

### ISSUE THREAD

**Issue by AJ311021** [DSE511-Team-Avatar/Team-Avatar#8]
- [x]  Decison Tree [Ehsan]
- [x]  Model optimization (hyperparameters tuning)
- [ ]  Basic error analysis using cross validation (mean squared error)
- [ ]  Feature extraction/importance (Can experiment with different categories (features, columns) combinations for the models)

**Comment by AJ311021** [comment]
Can try other models of interest here, maybe Decision Tree as one more variant.

**Comment by AJ311021** [comment]
Based on my preliminary observations of the Linear Regression model and a few studies on its tuning, it might be a good idea to consider and test the Ridge model as well.

**Comment by AEghasemi** [comment]
Sure. I will work on it

**Comment by AJ311021** [comment]
@AEghasemi you can work on Decision Tree Regression or you can choose any other better more appropriate model, that might be good for our task. You may want to do the search, up to you. With the exception of (LinReg, Lasso, Ridge, ElasticNet, RandomForest, SVM) these are under development now.

**Comment by AEghasemi** [comment]
Done.
