### ISSUE TITLE
Project parts division. Part 3. Modelling (d)

### ISSUE THREAD

**Issue by AJ311021** [DSE511-Team-Avatar/Team-Avatar#9]
- [x]  Support Vector Machine? [Pragya]
- [x]  Model optimization (hyperparameters tuning)
- [x]  Basic error analysis using cross validation (mean squared error)
- [x]  Feature extraction/importance (Can experiment with different categories (features, columns) combinations for the models)

**Comment by isifletcher** [comment]
Here is the equivalent of feature importance for SVM: https://stackoverflow.com/questions/41592661/determining-the-most-contributing-features-for-svm-classifier-in-sklearn
